language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.0
services:
  - memcached  
addons:
  hosts:
    - memcached      
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
os:
  - linux
script:
  - ./build.sh
  - ./test.sh
